/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CodingTrackRouteImport } from './routes/coding-track'
import { Route as CodingHistoryRouteImport } from './routes/coding-history'
import { Route as IndexRouteImport } from './routes/index'

const CodingTrackRoute = CodingTrackRouteImport.update({
  id: '/coding-track',
  path: '/coding-track',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingHistoryRoute = CodingHistoryRouteImport.update({
  id: '/coding-history',
  path: '/coding-history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coding-history': typeof CodingHistoryRoute
  '/coding-track': typeof CodingTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coding-history': typeof CodingHistoryRoute
  '/coding-track': typeof CodingTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coding-history': typeof CodingHistoryRoute
  '/coding-track': typeof CodingTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coding-history' | '/coding-track'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coding-history' | '/coding-track'
  id: '__root__' | '/' | '/coding-history' | '/coding-track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodingHistoryRoute: typeof CodingHistoryRoute
  CodingTrackRoute: typeof CodingTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/coding-track': {
      id: '/coding-track'
      path: '/coding-track'
      fullPath: '/coding-track'
      preLoaderRoute: typeof CodingTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding-history': {
      id: '/coding-history'
      path: '/coding-history'
      fullPath: '/coding-history'
      preLoaderRoute: typeof CodingHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodingHistoryRoute: CodingHistoryRoute,
  CodingTrackRoute: CodingTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
